#!/usr/bin/env perl
use strict; use warnings; use v5.28.0; use autodie;
use re '/a';
use open qw(:std :encoding(UTF-8));

use FindBin; use lib "$FindBin::Bin";
use _P_TxtTools;

$_ = slurp_fh;
html_tag_strip( qr{strong|em} );
html_tag_unnest( q(dd), q(p) );
$_ = slurp_fh( \*STDIN );

my $beg_rx     = qr{(?<= [\s>'"(=])}mx;  # WARN: ['"] match attr vals, but `help2man | pandoc` outputs none
my $url_scm_rx = qr{[a-z][a-z0-9]+:};
my $url_ch_rx  = qr{[\w/%.?=&+-]};
for my $rx(
  qr{`(.+?)`}ax,
  qr{( $beg_rx $url_scm_rx $url_ch_rx+ )}x,
  qr{( $beg_rx $url_ch_rx*(/$url_ch_rx | $url_ch_rx/)$url_ch_rx* )}x,
  qr{( $beg_rx (-[\[\]{}|\w?*=-]+) )}x,
) {
  s{$rx}{<code>$1</code>}g;
  html_tag_merge( q(code) ); html_tag_unnest( q(code), q(code) );
}
print;
